# Generated by Django 3.0.2 on 2020-01-22 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('weight', models.PositiveSmallIntegerField(default=0)),
                ('age', models.PositiveSmallIntegerField(default=0, help_text='Years')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pet/photo')),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
